package ru.ilnyrdiplom.bestedu.web.contracts;

public enum ErrorCodes {
    ACCESS_DENIED,
    NOT_VALID_ARGUMENT,
    UNKNOWN_ERROR,
    NOT_FOUND,
    REFRESH_TOKEN_EXPIRED,
    BAD_HTTP_REQUEST,
    LOGIN_EXISTS,
    INVALID_CODE,
    DISCIPLINE_ALREADY_EXISTS,
    IMPOSSIBLE_ACCESS_DISCIPLINE,
    WRONG_ACCOUNT_TYPE,
    EXERCISE_ALREADY_EXISTS,
    WRONG_CREDENTIALS,
    FILE_SIZE_EXCEEDED,
    WRONG_ACCESS_DISCIPLINE_STATUS;
}
