name: best-edu-deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set variables.
        run: |
          export JAVA_HOME="/opt/java/jdk1.8.0_281"
          export JDK_HOME="/opt/java/jdk1.8.0_281"
          export JRE_HOME="/opt/java/jdk1.8.0_281/jre"
          export M2_HOME="/opt/maven/apache-maven-3.6.3"
          export PATH="$PATH:$JAVA_HOME/bin:$JRE_HOME/bin:$M2_HOME/bin"
          source /etc/profile
      - name: Build jar archive.
        run: /opt/maven/apache-maven-3.6.3/bin/mvn clean install
      - name: Remove old application.
        run: sudo rm -rf /home/bestedu/best-edu-backend/*
      - name: Transfer artifact.
        run: sudo mv web-1.0-SNAPSHOT.jar /home/bestedu/best-edu-backend
