name: best-edu-deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Directory transfer.
        run: sudo mv ../best-edu-backend/ /home/bestedu/
