name: best-edu-deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set variables.
        run: |
          export PATH="$PATH:/opt/java/jdk1.8.0_281/bin:/opt/java/jdk1.8.0_281/jre/bin:/opt/maven/apache-maven-3.6.3/bin"
          source /etc/profile
      - name: Build jar archive.
        run: /opt/maven/apache-maven-3.6.3/bin/mvn clean install
      - name: Remove old application.
        run: sudo rm -rf /home/bestedu/best-edu-backend/*
      - name: Transfer artifact.
        run: sudo mv web-1.0-SNAPSHOT.jar /home/bestedu/best-edu-backend
