name: best-edu-deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Get user.
        run: echo "$USER"
      - name: Docker application init.
        run: sudo make init
