name: best-edu-deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Remove old application.
        run: sudo rm -rf /home/bestedu/best-edu-backend/*
      - name: Build jar archive.
        run: sudo /opt/maven/apache-maven-3.6.3/bin/mvn clean install
      - name: Transfer artifact.
        run: sudo mv web-1.0-SNAPSHOT.jar /home/bestedu/best-edu-backend
