name: best-edu-deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build jar archive.
        run: mvn -B clean install
      - name: Current directory.
        run: pwd
