name: best-edu-deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Remove old build path.
        run: sudo rm -rf /home/ilnur/projects/best-edu/backend/*
      - name: Copy to builds path.
        run: mv ./* /home/ilnur/projects/best-edu/backend
      - name: Docker application init.
        run: make init -C /home/ilnur/projects/best-edu/backend